# Generated by Django 2.0 on 2018-06-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_wars_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('climate', models.CharField(max_length=200)),
                ('terrain', models.CharField(max_length=200)),
                ('movie_appearances', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
